### PR TITLE
Update readme with indexes as an array

### PR DESCRIPTION
**Pull request by mdubus**

### CODE REVIEW

**Review by bidoubiwa — APPROVED** [review]
LGTM 🔥 🔥 🔥 🔥

**Comment by mdubus** [comment]
bad bors 😡

**Comment by mdubus** [comment]
bors merge

**Comment by mdubus** [comment]
bad bors 😡

**Comment by curquiza** [comment]
merge manually since bors is breaking an your branch is up to date with `main`

**Pull request merged**
