### PR TITLE
revert actions config - issue can no longer be reproduced

### LINKED ISSUE #159: Test job ran in CI is stuck on waiting for the web server to run
### Other

For a reason we ignore, the test in the CI started to fail on the 12 July 2022. Here is the [last test](https://github.com/meilisearch/gatsby-plugin-meilisearch/actions/runs/2655162703) that was successful.

This is the test command that used to work before the 12th:
```
"concurrently --kill-others -s first \"yarn playground:start\" \"wait-port http://localhost:8000/___graphql && jest --testPathPattern=tests\"",
```

Using the [concurrently tool](https://github.com/open-cli-tools/concurrently) the following is happening
- Kill any server that are still running: `--kill-others`
- Run the start command of the web server `-s first "yarn playground:start"`
- Run `wait-port` that waits on the playground to serve `localhost:8000/__graphql`
- Run the tests once the above route is served.

This used to work perfectly. 

For some reason that we are still trying to figure out, the CI is stuck after the start of the playground (see [failing CI](https://github.com/meilisearch/gatsby-plugin-meilisearch/runs/7397680361?check_suite_focus=true)).

```
[0] You can now view playground in the browser.
[0] ⠀
[0]   http://localhost:8000/
[0] ⠀
[0] View GraphiQL, an in-browser IDE, to explore your site's data and schema
[0] ⠀
[0]   http://localhost:8000/___graphql
[0] ⠀
[0] Note that the development build is not optimized.
[0] To create a production build, use gatsby build
[0] ⠀
[0] success Building development bundle - 17.638s
[0] success Writing page-data.json files to public directory - 0.076s - 9/9 118.[61](https://github.com/meilisearch/gatsby-plugin-meilisearch/runs/7397680361?check_suite_focus=true#step:7:62)/s 
## STUCK HERE
Error: The operation was canceled.
```

This part `Error: The operation was canceled.` was triggered by me clicking on `cancel workflow`. If I do not click on it, the CI ran for hours.

A possibility is that `wait-for` is listening for `localhost:8000` to be served but it never happens. Because it does not happen, the tests are not triggered as well. 

The best theory that we have now is that github changed the way they handle the github actions. Unfortunately I was not able to find any information on the subject.  

## Temporary solution

We removed the concurrently part and the wait-for with a more straightforward approach
- Start the playground in the background
- Wait for 30 seconds
- Run the tests

This solution is absolutely not something we would like to keep. 
Any help on finding out the issue is greatly appreciated 🙏

### PR DESCRIPTION
**Pull request by dadolhay**
# Pull Request

## Related issue
Fixes #159 

## What does this PR do?
- Reverts workaround in tests.yml (sleep 30)

I cannot reproduce the original issue anymore. [Successful CI run](https://github.com/dadolhay/gatsby-plugin-meilisearch/actions/runs/3220634401)

Thank you so much for contributing to Meilisearch!

### CODE REVIEW

**Comment by dadolhay** [comment]
@bidoubiwa Absolutely, I didn't find any other reference in the code for that script.
Removed, PR updated, CI is still passing on my fork.

**Review by bidoubiwa — APPROVED** [review]
LGTM 🔥

**Comment by bidoubiwa** [comment]
bors merge

**Comment by bidoubiwa** [comment]
bors merge

**Comment by bidoubiwa** [comment]
_This message is sent automatically_

Thanks again for contributing to Meilisearch :heart:
If you are participating in [Hacktoberfest](https://blog.meilisearch.com/contribute-hacktoberfest-2022/), and you would like to receive some gift from Meilisearch too, please complete [this form](https://meilisearch.typeform.com/to/idt5qugY).

**Pull request merged**
